### ISSUE TITLE
Elite C rev 4 thickness

### ISSUE THREAD

**Issue by keyboard-magpie** [brickbots/aball#1]
Current rev of elite C is now thicker than the one used in your build, c/o the mid mount USB. 

I think this needs a subtle mod to the vertical_frame.stl part. PCB is now 1.6mm thick. 

I have dremelled out the slots a little, as well as reduced the height of the USB socket end of the frame.

The remainder of the case works fine with the current elite C.

Happy to work on this if fusion files could be pushed.

**Comment by brickbots** [comment]
Hi  @keyboard-magpie!  Thank you so much for turning me on to this change and for providing the fitment information.  I've added a couple new STL's for the support frame to support this rev4 and also 34mm balls.  

I've also included the fusion file, thanks for pointing out that I had missed including it.  Hopefully its not overly messy and can make personalizing the design easier for folks 👍
