### ISSUE TITLE
X axis is inverted

### ISSUE THREAD

**Issue by pfn** [brickbots/aball#2]
I made one!

It's pretty cool, except flashing firmware is a pain. I mention this because the X axis was reversed for me. I had to update my config.h and flash again. I flashed the latest version at https://github.com/qmk/qmk_firmware/tree/master/keyboards/handwired/aball

```c
#define POINTING_DEVICE_INVERT_X
```

It would also be nice to change the design to use an adns9800 directly than a breakout that is only available from a single vendor.

![20220202_005021](https://user-images.githubusercontent.com/512197/152122346-47a34ba5-ecba-4431-bede-20d4d25dcc12.jpg)
![20220202_010121](https://user-images.githubusercontent.com/512197/152124491-644050cf-76b8-47bf-9f4e-2baeb5327028.jpg)

**Comment by brickbots** [comment]
Hi Hi!

I'm really digging the ball you are using there.  It's a wonderful looking build!

Thank you so much for spotting this bug.  When I converted over to the mainline ADNS drivers I removed all my custom code, including the axis fix, and forgot to enable it in the new libs.  I really appreciate your issue report and have started a PR in the QMK repo to fix it.  I'll also upload 

I know it can be expensive/difficult to source but the board from Jack enterprises makes the whole project approachable for people with limited electronics expertise.  Unfortunately, to work reliably, the ADNS generally requires some supporting circuitry.  There are some open source designs for a drop in replacement board, but it requires soldering some fairly small surface mount components and might not make sense as a one-off:
https://easyeda.com/pigboard/adns9800board

If I were to run a group buy of some sort, I'd have a more specific solution manufactured, but it'd take a bit of volume to make the economics work out.

Thanks again for sharing and spotting the bug!

**Comment by pfn** [comment]
Awesome, thanks for pointing out the BOM/board design on easyeda, that's a good step forward for breaking the reliance on a single vendor of the breakout board.

**Comment by roygbyte** [comment]
Been eyeing this project for a few months, possibly psyching myself up to build an aball. :)

How're you finding it now, a few months later, @pfn? Any best practices to pass along to someone waiting in the wings?

**Comment by pfn** [comment]
@roygbyte aball has been working great for me, but I would like to do some minor mods that aren't really a problem of aball: 
* integrate into the keyboard case for better stability
* design a case to better capture the ball from falling out
* design in a more accessible reset switch for flashing

otherwise, I use aball with my kyria daily, one of the best ergo setups for me, and the mods I described aren't really necessary to do, just something to occupy my time when I get bored.

**Comment by roygbyte** [comment]
That's good to know! My dream is actually to be able to control the aball with my foot :) For me that would be ergo-bliss!
