### ISSUE TITLE
Acrylic plates thickness

### ISSUE THREAD

**Issue by ziombo** [brickbots/aball#5]
I currently have acces to cut acrylis plates with +/- 2mm thickness. Based on the description for acylic case, I need:
seven 3mm layers in total, not including the base piece which can either be [...] or laser cut from 1.5mm metal or acrylic.
2 x middle_a.dxf - Middle piece with no side hole
2 x middle_b.dxf - Middle piece with side reset hole
1 x top_a.dxf
1 x top_b.dxf
1 x top_c.dxf

I'm trying to wrap my head around which part should have whick thickness. Is base supposed to be 1.5mm and every other part 3mm?

**Comment by brickbots** [comment]
Hi @ziombo!  Thanks for your question, I'll work to clarify that portion in the documentation.  All 7 of the layers that stack on top of the bottom piece should be 3mm thickness.  So you are aiming for a total height of about 21mm, but the hollow middle portion needs to be 12mm tall.  So if you are using 2mm stock, you'll need 3x the middle_an and 3x middle_b to make sure there is enough height to hold the mechanics.

The top pieces are less critical.  They keep the dust out and look nice, so you have more flexibility there.  You could just use the 2mm stock for 1x each piece and the top would be a bit lower-profile, but it will function the same.

For the bottom piece, it can be as thick or thin as desired.  As long as it's stiff enough, which should not be much of a problem at this size.  I think a single 2mm acrylic piece would be just fine if you didn't want to go metal for the bottom plate.

Hope this helps, please reach out with any questions!

**Comment by ziombo** [comment]
Thanks for the quick reply! It does make sense now and I passed this information to the shop that will cut these parts for me. One more thing. Do you know of any alternatives for the sensor you've [linked](https://www.tindie.com/products/jkicklighter/adns-9800-laser-motion-sensor/#shipping)? I'm from Europe and ordering this for US will cost me probably just as much as the sensor and will also take long. Any Europe or China based alternatives would be appreciated as it's usually easier and cheaper to order parts this way for me. Although that's not a deal breaker so if not then I'll get the sensor from the US.

**Comment by brickbots** [comment]
Happy to help!  The actual sensor package is fairly easy to get, but I did choose a breakout board which is made by a small (one person?) company in the US... which was not a great idea.  I've since started considering part availability more in my designs.....

This is a compatible open source version that you could build yourself, if you are okay with surface mount components:

https://github.com/kbjunky/ADNS9800

Not sure if this help and I definitely wish I had a better source for these sensors!
